# Generated by Django 5.1.1 on 2024-10-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='Persona',
        ),
    ]
