# Generated by Django 5.1.1 on 2024-10-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='estudiantes',
        ),
        migrations.AddField(
            model_name='curso',
            name='capacidadMaxima',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
        migrations.CreateModel(
            name='EstudianteYCurso',
            fields=[
                ('dni', models.CharField(default='SIN_DNI', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fechadeinicio', models.DateField()),
                ('fechefinal', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('nota_final', models.FloatField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
            ],
        ),
    ]
