# Generated by Django 5.1.1 on 2024-10-14 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cursos', models.CharField(max_length=100)),
                ('fecha_de_inicio', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(max_length=100)),
                ('costo', models.FloatField()),
            ],
        ),
    ]
